-- General recycling reference info, keyed by the material_type Gemini identifies.
-- Source: https://earth911.com/recycling-center-search-guides/
--
-- This is a lookup/reference table (not user data), so no RLS is needed beyond
-- restricting writes to service_role; everyone can read it.

create table public.recycling_app_material_info (
  material_type       text primary key,
  category            text not null,
  display_name        text not null,
  is_generally_recyclable boolean not null,
  instructions        text not null,
  source_url          text,
  created_at          timestamptz not null default now()
);

alter table public.recycling_app_material_info enable row level security;

grant select, insert, update, delete on public.recycling_app_material_info to service_role;
grant select on public.recycling_app_material_info to anon, authenticated;

create policy "recycling_app_material_info_select_all"
  on public.recycling_app_material_info for select
  using (true);

insert into public.recycling_app_material_info
  (material_type, category, display_name, is_generally_recyclable, instructions, source_url)
values
  ('pet_plastic_bottle', 'plastic', 'PET plastic bottle', true,
    'Widely accepted curbside. Empty and rinse first. See the linked guide for details.',
    'https://earth911.com/recycling-guide/how-to-recycle-plastic-bottles/'),
  ('hdpe_plastic_container', 'plastic', 'HDPE plastic container', true,
    'Widely accepted curbside. Empty and rinse first.', null),
  ('plastic_bag_or_film', 'plastic', 'Plastic bag or film', true,
    'Recyclable, but usually not curbside - most grocery/retail stores have a drop-off bin. See the linked guide.', null),
  ('styrofoam', 'plastic', 'Styrofoam / expanded polystyrene', true,
    'Recyclable at specialty drop-off locations, rarely curbside. See the linked guide for local options.', null),
  ('bubble_wrap', 'plastic', 'Bubble wrap', true,
    'Recyclable with plastic film drop-off (same as bags), not curbside. See the linked guide.',
    'https://earth911.com/home-garden/is-bubble-wrap-recyclable/'),
  ('black_plastic', 'plastic', 'Black-colored plastic', false,
    'Often can''t be sorted by recycling facility scanners. Check the linked guide before binning.',
    'https://earth911.com/how-to-recycle/recycling-mystery-black-colored-plastic/'),
  ('cardboard', 'paper', 'Cardboard', true,
    'Widely accepted curbside. Flatten and keep dry. See the linked guide for details.',
    'https://earth911.com/recycling-guide/how-to-recycle-cardboard/'),
  ('newspaper', 'paper', 'Newspaper', true,
    'Widely accepted curbside. Keep dry.',
    'https://earth911.com/recycling-guide/how-to-recycle-newspaper/'),
  ('paper_generic', 'paper', 'Paper', true,
    'Widely accepted curbside. Keep dry and free of food residue.',
    'https://earth911.com/recycling-guide/how-to-recycle-paper/'),
  ('paper_cup', 'paper', 'Paper cup', false,
    'Most have a plastic/wax lining and aren''t curbside recyclable. See the linked guide for exceptions.', null),
  ('paper_bag', 'paper', 'Paper bag', true,
    'Widely accepted curbside. Remove any handles/hardware.',
    'https://earth911.com/recycling-guide/how-to-recycle-paper-bags/'),
  ('book_or_magazine', 'paper', 'Book or magazine', true,
    'Widely accepted curbside; hardcovers may need the cover removed first. See the linked guide.',
    'https://earth911.com/recycling-guide/how-to-recycle-books-magazines/'),
  ('carton', 'paper', 'Carton', true,
    'Often accepted curbside. Empty and rinse first. See the linked guide for local acceptance.',
    'https://earth911.com/recycling-guide/how-to-recycle-carton/'),
  ('glass_bottle_or_jar', 'glass', 'Glass bottle or jar', true,
    'Widely accepted curbside. Empty and rinse first.',
    'https://earth911.com/recycling-guide/how-to-recycle-glass-bottles-jars/'),
  ('window_glass', 'glass', 'Window glass', true,
    'Recyclable, but usually needs a specialty glass/construction recycler, not curbside.',
    'https://earth911.com/home-garden/recycling-mystery-windows/'),
  ('kitchen_glassware', 'glass', 'Kitchen glassware', false,
    'Tempered/heat-resistant glass has a different melting point and usually isn''t recyclable with bottle glass.',
    'https://earth911.com/home-garden/recycling-mystery-old-kitchen-glassware/'),
  ('aluminum_can', 'metal', 'Aluminum can', true,
    'Widely accepted curbside. Empty and rinse first.',
    'https://earth911.com/recycling-guide/how-to-recycle-aluminum-cans/'),
  ('steel_or_tin_can', 'metal', 'Steel or tin can', true,
    'Widely accepted curbside. Empty and rinse first; labels can stay on.',
    'https://earth911.com/recycling-guide/how-to-recycle-tin-or-steel-cans/'),
  ('aluminum_foil', 'metal', 'Aluminum foil', true,
    'Often accepted curbside if clean and balled up. See the linked guide for local acceptance.',
    'https://earth911.com/recycling-guide/how-to-recycle-aluminum-foil/'),
  ('aerosol_can', 'metal', 'Aerosol can', true,
    'Often accepted curbside once empty. See the linked guide if contents remain.',
    'https://earth911.com/recycling-guide/how-to-recycle-aerosol-cans/'),
  ('propane_tank', 'metal', 'Propane tank', true,
    'Recyclable via an exchange program or hazardous waste facility, not curbside.',
    'https://earth911.com/how-to-recycle/recycling-mystery-propane-tanks/'),
  ('cell_phone', 'electronics', 'Cell phone', true,
    'Recyclable via manufacturer/retailer take-back or e-waste programs, not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-cell-phones/'),
  ('computer_or_laptop', 'electronics', 'Computer or laptop', true,
    'Recyclable via e-waste recyclers, often free. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-computers/'),
  ('computer_monitor', 'electronics', 'Computer monitor', true,
    'Recyclable via e-waste recyclers. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-computer-monitors/'),
  ('cd_or_dvd', 'electronics', 'CD or DVD', true,
    'Recyclable via specialty electronics/media recyclers. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-cds-tapes/'),
  ('ink_cartridge', 'electronics', 'Ink cartridge', true,
    'Recyclable via retailer take-back programs. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-ink-cartridges/'),
  ('small_appliance', 'electronics', 'Small appliance', true,
    'Recyclable via e-waste or scrap metal recyclers. Not curbside.', null),
  ('large_appliance', 'electronics', 'Large appliance', true,
    'Recyclable via bulk pickup or an appliance recycler. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-large-appliances/'),
  ('cfl_or_fluorescent_bulb', 'household_hazardous_waste', 'CFL or fluorescent bulb', true,
    'Contains mercury - never curbside. Recyclable via hazardous waste or retailer drop-off.',
    'https://earth911.com/recycling-guide/how-to-recycle-cfls/'),
  ('battery_household', 'household_hazardous_waste', 'Household battery', true,
    'Never curbside. Recyclable via battery drop-off points.', null),
  ('paint', 'household_hazardous_waste', 'Paint', true,
    'Never curbside. Recyclable via household hazardous waste or paint take-back programs.',
    'https://earth911.com/recycling-guide/how-to-recycle-paint/'),
  ('medication', 'household_hazardous_waste', 'Medication', false,
    'Never curbside or flushed. Use a pharmacy take-back or medication drop box for safe disposal.',
    'https://earth911.com/recycling-guide/how-to-recycle-unwanted-or-expired-medications/'),
  ('motor_oil_or_filter', 'automotive', 'Motor oil or filter', true,
    'Recyclable via auto parts stores or oil recycling drop-offs. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-motor-oil-and-filters/'),
  ('car_battery', 'automotive', 'Car battery', true,
    'Highly recyclable - nearly all auto parts retailers accept them. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-car-batteries/'),
  ('tire', 'automotive', 'Tire', true,
    'Recyclable via tire retailers or dedicated recycling facilities. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-tires/'),
  ('carpet', 'construction', 'Carpet', true,
    'Recyclable via manufacturer take-back or specialty recyclers. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-carpet/'),
  ('shingles', 'construction', 'Shingles', true,
    'Recyclable via construction waste or shingle recycling facilities. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-shingles/'),
  ('clothing_or_textile', 'household', 'Clothing or textile', true,
    'Recyclable via textile drop-offs; donate instead if still wearable. Not curbside.',
    'https://earth911.com/recycling-guide/how-to-recycle-clothing-accessories/'),
  ('furniture', 'household', 'Furniture', false,
    'Donate if usable; otherwise schedule a bulk waste pickup. Rarely a true recycling option.', null),
  ('cookware', 'household', 'Cookware', false,
    'Mixed materials/coatings usually make this non-recyclable; check for a scrap metal recycler.', null)
on conflict (material_type) do nothing;

